apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-general-config
  namespace: {{ .Values.kube_namespace }}
data:
  contractManagementServiceUrl: "{{ .Values.contractManagementServiceUrl }}"
  performanceServiceUrl: "{{ .Values.performanceServiceUrl }}"
  configurationServiceUrl: "{{ .Values.configurationServiceUrl }}"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-java-general-config
  namespace: {{ .Values.kube_namespace }}
data:
  contractManagementServiceUrl: "{{ .Values.contractManagementServiceUrl }}"
  performanceServiceUrl: "{{ .Values.performanceServiceUrl }}"
  configurationServiceUrl: "{{ .Values.configurationServiceUrl }}"
  FLYWAY_OWNER: "{{ .Values.java_env.FLYWAY_OWNER }}"
  OPM_ACS_ENABLED: "{{ .Values.java_env.OPM_ACS_ENABLED }}"
  OPM_CACHE_ENABLED: "{{ .Values.java_env.OPM_CACHE_ENABLED }}"
  BLOBSTORE_SERVICE_INSTANCE_NAME: "{{ .Values.java_env.BLOBSTORE_SERVICE_INSTANCE_NAME }}"
  CACHE_SERVICE_INSTANCE_NAME: "{{ .Values.java_env.CACHE_SERVICE_INSTANCE_NAME }}"
  blobstoreServiceUrl: "{{ .Values.java_env.blobstoreServiceUrl }}"
  PG_DB_URL: "{{ .Values.java_env.PG_DB_URL }}"
  APM_TIMSERIES_DEFAULT_DATASOURCE: "{{ .Values.java_env.APM_TIMSERIES_DEFAULT_DATASOURCE }}"
  HEART_BEAT_TAG: "{{ .Values.java_env.HEART_BEAT_TAG }}"
  ASSET_QUERY_TAG_LIMIT: "{{ .Values.java_env.ASSET_QUERY_TAG_LIMIT }}"
  OPM_SERVICE_INSTANCE_NAME: "{{ .Values.java_env.OPM_SERVICE_INSTANCE_NAME }}"
  AWS_REGION: "{{ .Values.java_env.AWS_REGION }}"
  PG_DB_PASSWORD: "{{ .Values.java_env.PG_DB_PASSWORD }}"
  valueStoreTimeout: "{{ .Values.java_env.valueStoreTimeout }}"
  RECOVERY_FACTOR_TIMEOUT: "{{ .Values.java_env.RECOVERY_FACTOR_TIMEOUT }}"
  PG_DB_NAME: "{{ .Values.java_env.PG_DB_NAME }}"
  ENCRYPTION_ENABLED: "{{ .Values.java_env.ENCRYPTION_ENABLED }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.java_env.SPRING_PROFILES_ACTIVE }}"
  ENABLE_SERVER_SIDE_ENCRYPTION: "{{ .Values.java_env.ENABLE_SERVER_SIDE_ENCRYPTION }}"
  ADMIN_UOM_SERVICE_CACHE: "{{ .Values.java_env.ADMIN_UOM_SERVICE_CACHE }}"
  APM_TS_TAG_QUERY_LIMIT: "{{ .Values.java_env.APM_TS_TAG_QUERY_LIMIT }}"
  OPM_ACS_URL: "{{ .Values.java_env.OPM_ACS_URL }}"
  OPM_ACS_ENABLED: "{{ .Values.java_env.OPM_ACS_ENABLED }}"
  LOCAL_S3_ROOT_PATH: "{{ .Values.java_env.LOCAL_S3_ROOT_PATH }}"
  FLASK_ENV: "{{ .Values.java_env.FLASK_ENV }}"
  APM_TS_DEFAULT_DATA_SOURCE: "{{ .Values.java_env.APM_TS_DEFAULT_DATA_SOURCE }}"
  ENCRYPTION_PASSWORD: "{{ .Values.java_env.ENCRYPTION_PASSWORD }}"
  OPM_SERVICE_INSTANCE_NAME: "{{ .Values.java_env.OPM_SERVICE_INSTANCE_NAME }}"
  ENCRYPTION_CONFIG: "{{ .Values.java_env.ENCRYPTION_CONFIG }}"
  ONPREM_URL: "{{ .Values.java_env.ONPREM_URL }}"
  ENCRYPTION_SERVICE_INSTANCE_NAME: "{{ .Values.java_env.ENCRYPTION_SERVICE_INSTANCE_NAME }}"
  OPM_APP_NAME: "{{ .Values.java_env.OPM_APP_NAME }}"
  OPM_SPACE_NAME: "{{ .Values.java_env.OPM_SPACE_NAME }}"
  DEFAULT_ERROR: "{{ .Values.java_env.DEFAULT_ERROR }}"
  OPM_SERVICE_INSTANCE_NAME: "{{ .Values.java_env.OPM_SERVICE_INSTANCE_NAME }}"
  DATA_DURATION: "{{ .Values.java_env.DATA_DURATION }}"
  BADVALUE_CONFIG_FILE: "{{ .Values.java_env.BADVALUE_CONFIG_FILE }}"
  OPMPI_HB_GOODQUALITY: "{{ .Values.java_env.OPMPI_HB_GOODQUALITY }}"
  SERVICE_REGISTRY_ENABLED: "{{ .Values.java_env.SERVICE_REGISTRY_ENABLED }}"
  abc: "xyz"
  
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-python-general-config
  namespace: {{ .Values.kube_namespace }}
data:
  FLASK_APP: "{{ .Values.python_env.FLASK_APP }}"
  REDIS_CACHE: "{{ .Values.python_env.REDIS_CACHE }}"
  PYTHONUNBUFFERED: "{{ .Values.python_env.PYTHONUNBUFFERED }}"
  COMMON_SERVICE_URL: "{{ .Values.python_env.COMMON_SERVICE_URL }}"
  OPM_ACS_URL: "{{ .Values.python_env.OPM_ACS_URL }}"
  MIGRATION_S3_COPY: "{{ .Values.python_env.MIGRATION_S3_COPY }}"
  ENCRYPTION_ENABLED: "{{ .Values.python_env.ENCRYPTION_ENABLED }}"
  PROFILE: "{{ .Values.python_env.PROFILE }}"
  OPM_ACS_ENABLED: "{{ .Values.python_env.OPM_ACS_ENABLED }}"
  LOCAL_S3_ROOT_PATH: "{{ .Values.python_env.LOCAL_S3_ROOT_PATH }}"
  FLASK_ENV: "{{ .Values.python_env.FLASK_ENV }}"
  APM_TS_DEFAULT_DATA_SOURCE: "{{ .Values.python_env.APM_TS_DEFAULT_DATA_SOURCE }}"
  xyz: 123
  ENCRYPTION_PASSWORD: "{{ .Values.python_env.ENCRYPTION_PASSWORD }}"
  OPM_SERVICE_INSTANCE_NAME: "{{ .Values.python_env.OPM_SERVICE_INSTANCE_NAME }}"
  ENCRYPTION_CONFIG: "{{ .Values.python_env.ENCRYPTION_CONFIG }}"
  ABSOLUTE_LOG_PATH: "{{ .Values.python_env.ABSOLUTE_LOG_PATH }}"
  OPM_APP_NAME: "{{ .Values.python_env.OPM_APP_NAME }}"
  OPM_SPACE_NAME: "{{ .Values.python_env.OPM_SPACE_NAME }}"
  ONPREM_URL: "{{ .Values.python_env.ONPREM_URL }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-vcap-general-config
  namespace: {{ .Values.kube_namespace }}
data:
  VCAP_SERVICES: |
    "{\"user-provided\": [{\"name\": \"ged-opmpi-postgres-aws-cups\"\
            , \"tags\": [], \"volume_mounts\": [], \"label\": \"user-provided\", \"\
            syslog_drain_url\": \"\", \"credentials\": {\"username\": \"uqc74948uuyu0zo7\"\
            , \"database\": \"postgres_aws\", \"db_password\": \"0rd723shh6d2cn6t0hbyw797t\"\
            , \"hostname\": \"db-987deff8-f17c-429b-9e36-a72cecf721ef.c7uxaqxgfov3.us-west-2.rds.amazonaws.com\"\
            , \"uri\": \"postgres://uqc74948uuyu0zo7:0rd723shh6d2cn6t0hbyw797t@db-987deff8-f17c-429b-9e36-a72cecf721ef.c7uxaqxgfov3.us-west-2.rds.amazonaws.com:5432/postgres_aws\"\
            , \"host\": \"db-987deff8-f17c-429b-9e36-a72cecf721ef.c7uxaqxgfov3.us-west-2.rds.amazonaws.com\"\
            , \"db_name\": \"postgres_aws\", \"db_user\": \"uqc74948uuyu0zo7\", \"\
            password\": \"0rd723shh6d2cn6t0hbyw797t\"}}, {\"name\": \"opm-config\"\
            , \"tags\": [], \"volume_mounts\": [], \"label\": \"user-provided\", \"\
            syslog_drain_url\": \"\", \"credentials\": {\"redis_password\": \"password123456789\"\
            , \"blobstoreServiceUrl\": \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-blobstore\"\
            , \"contractManagementServiceUrl\": \"http://ged-opmpi-contract-management-service.opm-pi-dev.svc.cluster.local:5053\"\
            , \"apmUserUrl\": \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-users\"\
            , \"alertUrl\": \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-alerts\"\
            , \"blobstore_access_key_id\": \"AKIAZAX6MP3CC63VHLHH\", \"computeServiceUrl\"\
            : \"http://ged-opmpi-compute-service.opm-pi-dev.svc.cluster.local:5006\"\
            , \"encryption_password\": \"passwordpassword\", \"apmAlertsUrl\": \"\
            https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-alert\"\
            , \"adminServiceUrl\": \"http://ged-opmpi-admin-service.opm-pi-dev.svc.cluster.local:5051\"\
            , \"notificationServiceUrl\": \"http://ged-opmpi-notification-service.opm-pi-dev.svc.cluster.local:5011\"\
            , \"blobstore_secret_access_key\": \"BUksSqgldd24xQ/pKNbnpYj3wgaMwCjhtRUxOAkM\"\
            , \"adminCoreServiceUrl\": \"http://ged-opmpi-admin-core-service.opm-pi-dev.svc.cluster.local:5052\"\
            , \"apmTimeseriesQueryUrl\": \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-timeseries-dac\"\
            , \"blobstore_host\": \"s3-us-west-2.amazonaws.com\", \"apmCasesUrl\"\
            : \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-cases\"\
            , \"apmAssetQueryUrl\": \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-asset\"\
            , \"uomServiceUrl\": \"https://ged-opmpi-aws-gateway-service-dev.run.aws-usw02-pr.ice.predix.io/route/opm-uom\"\
            , \"blobstore_bucket_name\": \"bucket-ca3465e5-1622-494f-9495-2deba1ec0943\"\
            , \"blobstore_url\": \"https://bucket-ca3465e5-1622-494f-9495-2deba1ec0943.s3-us-west-2.amazonaws.com\"\
            , \"redis_ssl\": \"true\", \"redis_host\": \"master.apmpi-dev-cache.h2h8as.usw2.cache.amazonaws.com\"\
            , \"commonServiceUrl\": \"http://ged-opmpi-common-service.opm-pi-dev.svc.cluster.local:5058\"\
            , \"auditServiceUrl\": \"http://ged-opmpi-audit-service.opm-pi-dev.svc.cluster.local:5060\"\
            , \"redis_port\": \"6379\", \"configurationServiceUrl\": \"http://ged-opmpi-configuration-service.opm-pi-dev.svc.cluster.local:5003\"\
            }}]}"
